# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160302_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.BinaryField()),
            ],
        ),
    ]
