# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_settingentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingentry',
            name='key',
        ),
        migrations.AlterField(
            model_name='settingentry',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
