# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160303_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingentry',
            name='type',
            field=models.IntegerField(choices=[(0, 'pickle'), (1, 'string')], default=1),
            preserve_default=False,
        ),
    ]
