# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_settingentry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingentry',
            name='value',
            field=models.TextField(),
        ),
    ]
