# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160303_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='SettingEntry',
        ),
    ]
